---
- name: Ensure repository is cloned and set to desired version
  no_log: "{{ no_output }}"
  become: True
  become_user: "{{ user }}"
  git:
    repo: "{{ repository }}"
    dest: "{{ app_folder }}"
    version: "{{ version }}"
    force: True
    accept_hostkey: True

- name: Compile Docker Compose configuration
  no_log: "{{ no_output }}"
  become: True
  become_user: "{{ user }}"
  template:
    src: "compose.yml.j2"
    dest: "{{ app_folder }}/docker-compose.yml"

- name: Create systemd services
  no_log: "{{ no_output }}"
  become: True
  template:
    src: "systemd.j2"
    dest: "/etc/systemd/system/{{ item.name | default(boot_default_name) }}.service"
  with_items: "{{ boot_scripts | default([]) }}"

- name: Make sure boot scripts are running and enabled
  no_log: "{{ no_output }}"
  become: True
  systemd:
    state: started
    enabled: True
    name: "{{ item.name }}"
    daemon_reload: True
  with_items: "{{ boot_scripts | default([]) }}"

- name: Make sure boot scripts are restarted
  no_log: "{{ no_output }}"
  become: True
  systemd:
    state: restarted
    name: "{{ item.name }}"
    daemon_reload: True
  with_items: "{{ boot_scripts | default([]) }}"
